### PR TITLE
Update docs and compress images more

### PR DESCRIPTION
**Pull request by XhmikosR**

### CODE REVIEW

**Comment by rock3r** [comment]
I've changed a couple of things on the README and merged. Thanks!

**Comment by XhmikosR** [comment]
You basically reverted all my README changes from what I can tell.

**Comment by XhmikosR** [comment]
Even the typo fixes and everything.

Oh well, I made my contribution, you chose to revert it so it's your own decision.

For reference, [this](https://github.com/XhmikosR/FWeather/commit/697cfd3bb50dd65b1cbc2ea5a56f06ddbd636c2e) is a revert of your patch, which is basically my original patch.

**Comment by rock3r** [comment]
That wasn't my intention. The history has somehow been messed up between merges; I actually had your version of the README with a couple of tweaks in place. Don't know what happened, I'm restoring the right version.

**Comment by rock3r** [comment]
Fixed again as of 5a39cad

**Comment by XhmikosR** [comment]
OK, I thought it was done on purpose since it was a clear revert.

**Comment by rock3r** [comment]
I did a revert, because it was easier to merge into develop first and then manually re-.apply the changes :) But then I had a commit with all the changes, that was somehow lost in the merge. I have no idea how.

**Comment by XhmikosR** [comment]
git can be tricky sometimes, unfortunately. No worries :)

**Pull request merged**
