### PR TITLE
Images

### PR DESCRIPTION
**Pull request by XhmikosR**
I used PNGOut /r, deflopt and zopfli. All conversions are lossless.

I haven't tested it in a real build on my phone, so please try it.

Size changes  https://gist.github.com/XhmikosR/0aad57c5eea1787dae3c

### CODE REVIEW

**Comment by rock3r** [comment]
Thanks for your pull request!

I'm not going to merge it though, because the first commit doesn't change anything but a few whitespaces (which I'll merge manually in a few minutes) and the second commit has become useless, as I've already PNG-crunched all drawables as of fa2e7ef this afternoon.

Sorry!

**Comment by XhmikosR** [comment]
Nope, the second patch is **after** your patch.

This is the best compression workflow I've found and your way is simply not as good ;)

**Comment by rock3r** [comment]
Uh, ok. Can't figure out why there should be any appreciable difference in the PNG sizes though. I'm checking this out more carefully and I'll merge it if it's actually the case.

**Comment by XhmikosR** [comment]
Just test if everything shows up right on your phone.

Size-wise this is the best you will get without losing quality.

zopfli is a new compression algorith compatible with zlib decoders, developed by google and offers ~5% better compression, but it's very slow. That, along with the multiple passes and PNGOut and various blocksizes offers the best compression.

**Comment by rock3r** [comment]
Thanks!

**Comment by XhmikosR** [comment]
Thanks. Do you have the size difference for the apk since v2.1.3?

**Comment by rock3r** [comment]
Yes. Release builds.

**2.1.3** 1,53 MB (1.608.238 bytes)
**now** 1,53 MB (1.608.076 bytes)

**Comment by XhmikosR** [comment]
OK, thanks!

**Pull request merged**
