### PR TITLE
Language override preference

### PR DESCRIPTION
**Pull request by danybony**
mmm
I sill have to understand how this pull-request thing works...
Please ignore the changes to the .iml and .ipr files.

Anyway I added a preference in the settings activity to let the user choose the language of displayed text in the widget.

### CODE REVIEW

**Comment by rock3r** [comment]
Thanks Daniele! Will review and merge it into 1.2 after we get 1.1 out in the wild :)

**Comment by frapontillo** [comment]
Can you please pull the latest commits and update this PR?

**Comment by rock3r** [comment]
Yes, could be really useful, this is a pretty old codebase and a huge pain
in the ass to merge :)
While you're at it, I'd find very useful that the first item in the
ListPreference was an "Auto (system language)" option, which would be the
default one.

Thaaaanks! Owe you a beer

PS: please define preference key constants in the .global.Const$Preferences
class, to be consistent with the rest of the app.

**Comment by danybony** [comment]
Gentlemen, here is what you asked for

**Comment by rock3r** [comment]
Thanks man!

**Comment by rock3r** [comment]
No worries, I'll do it myself.

**Comment by frapontillo** [comment]
Nice PR, everything is working just fine ;)
I am just going to add and enable the default value for the preference.

**Pull request merged**
